### ISSUE TITLE
Got Error after update extension to 4.4.2

### ISSUE THREAD

**Issue by kbenyedder** [tpwd/ke_search#109]
Call to undefined method TYPO3\CMS\Core\Database\Query\QueryBuilder::executeQuery() 

Typo3 Version 10.4.27
Faceted Search : 4.4.2
Faceted Search Premium : 4.1.0

see the attached screenshot:

![image](https://user-images.githubusercontent.com/66422450/173045959-4bddfb87-99c0-43ba-b9d3-2fdbd39ffa8a.png)

Greeting beny

**Comment by christianbltr** [comment]
Which TYPO3 version are you using?

**Comment by kbenyedder** [comment]
10.4.27

**Comment by christianbltr** [comment]
This has been fixed in 4.4.3
