### ISSUE TITLE
Forked repo not searchable

### ISSUE THREAD

**Issue by mikestreety** [tpwd/ke_search#11]
Hey,

Is it possible to re-create the repo on Github as a non-forked version? I utilise the code search function on Github _a lot_ when investigating issues and, since being forked, I get the following message:

> Sorry, forked repositories are not currently searchable.

If this is the main repo going forward I would really appreciate the ability to search the code.

Thanks!

**Comment by christianbltr** [comment]
I agree, that would be good, but it seems not to be possible to configure that.

I asked the GitHub support to delete the fork dependency according to https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#commit-was-made-in-a-fork

**Comment by mikestreety** [comment]
Thanks 👍 would be a great help

**Comment by christianbltr** [comment]
tpwd/ke_search is now detached into a standalone repository.

**Comment by mikestreety** [comment]
That was swift! Thank you !
