### ISSUE TITLE
Record Storage Page is ignored

### ISSUE THREAD

**Issue by joachimruhs** [tpwd/ke_search#113]
Up to version 4.4.1 everything works fine, with version 4.4.2 and 4.4.4 the Record Storage Page is ignored and the Plugin finds no results.
I have to do a workaround and place the plugin on a page where the searchdata is located.

**Comment by joachimruhs** [comment]
Hi,
that are my pages:
On page Suche the Searchbox plugin is located,
on page Searchresult the list plugin is located,
on page Searchdata the Searchdata of the indexeris located.

I'm using TYPO3 10.4.28.
 
![image](https://user-images.githubusercontent.com/51224372/174256487-845c553d-c8ec-4b6e-8f9a-b74b6a713462.png)

Regards

**Comment by joachimruhs** [comment]
Hi,
you use the same page with searchbox and search result plugins?

**Comment by christianbltr** [comment]
Yes, I did. 
Using two different pages for the search box and search resultlist I get an error. I will look into it.

**Comment by christianbltr** [comment]
This has been fixed in current master and will be in version 4.4.5.

**Comment by joachimruhs** [comment]
Thx...
