### ISSUE TITLE
Conflict between field name "recursive" and MySQL keyword "recursive" (Branch `compat8`)

### ISSUE THREAD

**Issue by mawo** [tpwd/ke_search#115]
Usage of the field name `recursive` throws an error in newer MySQL / MariaDB versions.

It can be fixed easily by adding backticks to the field name:

<img width="636" alt="image" src="https://user-images.githubusercontent.com/1675936/174979912-3d40dfe3-4006-4726-9f39-ad3a697be547.png">

**Comment by christianbltr** [comment]
I don't think that there will be another version of ke_search for TYPO3 8, but I'm merging this because it might be help others. Thanks.
