### ISSUE TITLE
IndexerBase.php SQL Issue

### ISSUE THREAD

**Issue by abasheleli** [tpwd/ke_search#117]
“IndexerBase.php”
Line: ~142

Instead of:

$where[] = $queryBuilder->expr()->in('pages.uid', implode(',', $uids));

should be 

if(is_array($uids))
        {
            if(count($uids) > 0)
            {
                $where[] = $queryBuilder->expr()->in('pages.uid', implode(',', $uids));
            }
        }

or something like that. 

In case of empty $uids resulting SQL have empty IN clause...

**Comment by christianbltr** [comment]
related to #66
