### ISSUE TITLE
Classes/Lib/SearchHelper.php

### ISSUE THREAD

**Issue by abasheleli** [tpwd/ke_search#118]
Line ~ 274

case 'file':

in else section

$filePath = Environment::getPublicPath() . '/' . $resultRow['directory'] . $resultRow['title'];

Environment::getPublicPath() returns absolute path to root and
$resultRow['directory'] already have absolute path to the file.... so resulting

$filePath is always wrong... 

and link will never be set

**Comment by christianbltr** [comment]
Thanks for reporting. This has been fixed in current master and will be in the next version.
