### ISSUE TITLE
search behaviour and operators

### ISSUE THREAD

**Issue by FurtFan86** [tpwd/ke_search#121]
Hello I have a question about the docomentation https://docs.typo3.org/p/teaminmedias-pluswerk/ke_search/main/en-us/Behaviour/Options.html and the search behaviour. How does "Conjunction: The result must contain the word" work? I read and understand it like this: Find all results with the search term between the quotes AND what is after the plus sign. but in the search results entries are output with the search term between the quotes or with what is after the plus sign. Is this the correct behaviour? This could also be observed on another website with ke_search. I expected that only search results with the search term and the term behind the plus would be displayed.

**Comment by christianbltr** [comment]
You are right, the documentation is not complete here. To use the "+" and "-" conjunctions "Enable partial word search" (`basic.enablePartSearch`) in the extension setting must turned **off**.

Also, if you want to to find only results which include **both** search words, you need to add the "+" to both search words, eg.

```
+"french cooking" +eggs
```
