### ISSUE TITLE
Error when adding filter options

### ISSUE THREAD

**Issue by bocianl** [tpwd/ke_search#123]
Hello,

TYPO3 version: 11.5.14
PHP: 7.4.30
ke_search:  4.4.5
installation without composer

When adding Filter options there is an error:

An exception occurred while executing 'SELECT `uid`, `l10n_state`, `sys_language_uid`, `l10n_parent` FROM `tx_kesearch_filters` WHERE (`uid` IN (?)) AND (`t3ver_wsid` = 0) AND (`tx_kesearch_filters`.`deleted` = 0)' with params [1]: Unknown column 't3ver_wsid' in 'where clause'

**Comment by h3nn3s** [comment]
This issue is caused by a TYPO3 core bug

**Comment by bocianl** [comment]
Thank you.
