### ISSUE TITLE
Error in resultrow.title while indexing tt_address > 6.0.0

### ISSUE THREAD

**Issue by sudotec-gbr** [tpwd/ke_search#125]
tt_address used to fill the database-field `tt_address.name` with` first_name`+`last_name`. 
This behaviour changed with version 6. 
Now, the field `name` remains empty in newly created tt_address-records.

In ke_search, display of search results of type "tt_address" are based on the field `name` and are empty now.

**Comment by christianbltr** [comment]
I could no reproduce this issue (tested with ke_search 4.5.0 and tt_address 6.1.0).

ke_search checks if the field `name` is empty and if yes uses `first_name` and `last_name` instead. See https://github.com/tpwd/ke_search/blob/master/Classes/Indexer/Types/TtAddress.php#L110

Could you check this again?

**Comment by sudotec-gbr** [comment]
You are right - you can close the issue.
I overlooked a hook in my installation. 
Sorry for the noise!

**Comment by christianbltr** [comment]
No problem. Thanks for the reply.
