### ISSUE TITLE
Error with scheduler runing in full mode

### ISSUE THREAD

**Issue by joachimruhs** [tpwd/ke_search#127]
Hello,
ke_search version 4.5.1
When running the indexer with sheduler in full mode I got the error

Core: Exception handler (CLI): Uncaught TYPO3 Exception: syntax error, unexpected 'EventDispatcherInterface' (T_STRING), expecting function (T_FUNCTION) or const (T_CONST) | ParseError thrown in file /var/www/vhosts/roha-fotothek.de/httpdocs/typo3conf/ext/ke_search/Classes/Indexer/IndexerRunner.php in line 85 

Regards

**Comment by christianbltr** [comment]
What PHP version do you use?

**Comment by joachimruhs** [comment]
Php version is 7.4.32

**Comment by christianbltr** [comment]
I could not reproduce the issue with PHP 8.1 or 7.4.

Could it be that you use PHP 7.2 or lower on the command line? That would explain the error message because in that line there is a typed property defined which is only available in PHP 7.4 or higher.

**Comment by joachimruhs** [comment]
Hello,
I just checked the php version when user root is on.
PHP 7.2.24-0ubuntu0.18.04.13 (cli)

Ok, thats seem to be the error.

Thx for the info

   Joachim Ruhs
