### ISSUE TITLE
sword is an array in query params, then a TypeError is thrown

### ISSUE THREAD

**Issue by brotkrueml** [tpwd/ke_search#137]
I had a request with the following query string:

    ?tx_kesearch_pi1%5Bpage%5D=1&tx_kesearch_pi1%5Bsword%5D%5B%24eq%5D=the"

Or a bit nicer formatted:

    tx_kesearch_pi1[page]=1
    tx_kesearch_pi1[sword][$eq]=the

Which throws a TypeError:

    trim(): Argument #1 ($string) must be of type string, array given

Stack Trace:

    tpwd/ke_search/Classes/Lib/PluginBaseHelper.php in Tpwd\KeSearch\Lib\PluginBaseHelper::cleanPiVars at line 154
    tpwd/ke_search/Classes/Lib/Pluginbase.php in Tpwd\KeSearch\Lib\Pluginbase::init at line 198
    tpwd/ke_search/Classes/Plugins/SearchboxPlugin.php in Tpwd\KeSearch\Plugins\SearchboxPlugin::main at line 63
    ...

I see this problem the first time. It is this part of code:

    case 'sword':
        $piVars[$key] = trim($piVars[$key]);
        break;

which is called from

    $this->piVars = $this->div->cleanPiVars($this->piVars, $additionalAllowedPiVars);

Is this `$eq` key a valid option in ke_search? But if it is or is not, perhaps the variable should be guarded to be really a string? What do you think?

**Comment by christianbltr** [comment]
Thanks. Yes, sword should always be a string. That's fixed now in master.
