### ISSUE TITLE
PHP 8.2 deprecations in frontend search

### ISSUE THREAD

**Issue by brotkrueml** [tpwd/ke_search#138]
With PHP 8.2 some deprecation messages are given in the logs when using the search plugin in frontend. All of them are thrown because dynamic properties are deprecated: https://wiki.php.net/rfc/deprecate_dynamic_properties

While this can be circumvented with the class attribut `#[AllowDynamicProperties]`, after looking at them they are revealing a design flaw or are just setting class properties which are not used later on.

## `SearchboxPlugin::$ms` and `ResultlistPlugin::$ms`

    PHP Runtime Deprecation Notice: Creation of dynamic property Tpwd\KeSearch\Plugins\SearchboxPlugin::$ms is deprecated in /var/www/html/vendor/tpwd/ke_search/Classes/Plugins/SearchboxPlugin.php line 50
    PHP Runtime Deprecation Notice: Creation of dynamic property Tpwd\KeSearch\Plugins\ResultlistPlugin::$ms is deprecated in /var/www/html/vendor/tpwd/ke_search/Classes/Plugins/ResultlistPlugin.php line 50

The dynamic property `ms` is set but never used later on (neither in the class nor in the parent classes). So I think they can be removed safely:

```diff
     public function main($content, $conf)
     {
-        $this->ms = round(microtime(true) * 1000);
-
         $typoScriptService = GeneralUtility::makeInstance(TypoScriptService::class);
```

## `SearchboxPlugin::$swordValue`

    PHP Runtime Deprecation Notice: Creation of dynamic property Tpwd\KeSearch\Plugins\SearchboxPlugin::$swordValue is deprecated in /var/www/html/vendor/tpwd/ke_search/Classes/Lib/Pluginbase.php line 381

This can be adjusted like this:

```diff
         if (!empty($searchString) && $searchString != $searchboxDefaultValue) {
-            $this->swordValue = $searchString;
+            $swordValue = $searchString;
         } else {
-            $this->swordValue = '';
+            $swordValue = '';
         }

-        $this->fluidTemplateVariables['searchword'] = htmlspecialchars($this->swordValue);
+        $this->fluidTemplateVariables['searchword'] = htmlspecialchars($swordValue);
```

## `SearchboxPlugin::$pi_USER_INT_obj` and `ResultlistPlugin::$pi_USER_INT_obj`

    PHP Runtime Deprecation Notice: Creation of dynamic property Tpwd\KeSearch\Plugins\SearchboxPlugin::$pi_USER_INT_obj is deprecated in /var/www/html/vendor/tpwd/ke_search/Classes/Plugins/SearchboxPlugin.php line 58
    PHP Runtime Deprecation Notice: Creation of dynamic property Tpwd\KeSearch\Plugins\ResultlistPlugin::$pi_USER_INT_obj is deprecated in /var/www/html/vendor/tpwd/ke_search/Classes/Plugins/ResultlistPlugin.php line 58

These are not used, also not in the AbstractPlugin. Maybe they are outdated, but I haven't found something about it in the changelogs. So, has to be checked.

## `ResultlistPlugin::$currentRowNumber`

    PHP Runtime Deprecation Notice: Creation of dynamic property Tpwd\KeSearch\Plugins\ResultlistPlugin::$currentRowNumber is deprecated in /var/www/html/vendor/tpwd/ke_search/Classes/Lib/Pluginbase.php line 767

This is quite a dirty one, as it sets explicitly a dynamic property to be available in a hook and unsets it afterwards:

```php
       if (is_array($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['ke_search']['additionalResultMarker'] ?? null)) {
           // make curent row number available to hook
           $this->currentRowNumber = $resultCount;
           foreach ($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['ke_search']['additionalResultMarker'] as $_classRef) {
               $_procObj = GeneralUtility::makeInstance($_classRef);
               $_procObj->additionalResultMarker($tempMarkerArray, $row, $this);
           }
           unset($this->currentRowNumber);
       }
```

## `ResultlistPlugin::$limit` and `ResultlistPlugin::$dbLimit`

    PHP Runtime Deprecation Notice: Creation of dynamic property Tpwd\KeSearch\Plugins\ResultlistPlugin::$limit is deprecated in /var/www/html/vendor/tpwd/ke_search/Classes/Lib/Pluginbase.php line 1028
    PHP Runtime Deprecation Notice: Creation of dynamic property Tpwd\KeSearch\Plugins\ResultlistPlugin::$dbLimit is deprecated in /var/www/html/vendor/tpwd/ke_search/Classes/Lib/Pluginbase.php line 1035

`limit` and `dbLimit` are not used in the class (and also not in the parent classes), so I think these lines can be removed.

**Comment by christianbltr** [comment]
Which version of ke_search did you use in your test?
These already all be fixed in the current master due to the recent fixes of errors reported by PHPStan.
Could you check that?

**Comment by brotkrueml** [comment]
I used the latest release (4.5.1) but haven't checked master branch. I switched now to master and as I can see, there are no deprecations anymore. Thanks.
