### ISSUE TITLE
Problem with workspaces. Contend in editing indexed

### ISSUE THREAD

**Issue by alexmari81** [tpwd/ke_search#139]
I have typo3 11.5 I use ke_search 4.5.1.

I created a workspace for editing and there are content that are in "editing" status.

Result page of ke_search display contents that are not approved and aro not in live workspace, how can i resolve?

**Comment by christianbltr** [comment]
I cannot reproduce this for pages and text content elements. And there is already a check implemented if content is not in the live stage.

What kind of content are you indexing? Is it some kind of extension records?

**Comment by alexmari81** [comment]
It is a "header" content

**Comment by alexmari81** [comment]
Hi, i printed the query for tt_content and i have:

`SELECT `uid`, `pid`, `header`, `CType`, `sys_language_uid`, `header_layout`, `fe_group`, `file_collections`, `filelink_sorting`, `records`, `bodytext` FROM `tt_content` WHERE (`pid` = :dcValue1) AND (CType="text" OR CType="textmedia" OR CType="textpic" OR CType="bullets" OR CType="table" OR CType="html" OR CType="header" OR CType="uploads" OR CType="shortcut") AND ((`tt_content`.`deleted` = 0) AND (`tt_content`.`hidden` = 0) AND (`tt_content`.`starttime` <= 1673362080) AND ((`tt_content`.`endtime` = 0) OR (`tt_content`.`endtime` > 1673362080)))`

there is no trace of versioning so i added this code to the query:
```
  ->andWhere(
                        $queryBuilder->expr()->eq('t3ver_state', $queryBuilder->createNamedParameter(0, \PDO::PARAM_INT)))
```
               
and it works as i expected.

I don't know why there isn't this restriction, maybe i missed something?

**Comment by christianbltr** [comment]
My fault, the check was only implemented for pages, not for content elements.

The check is now implemented for content elements also. The patch is in version 4.6.1 which has just been released.
