### ISSUE TITLE
[FEATURE] Extend Hook modifyFilters and add parameter $this->conf

### ISSUE THREAD

**Issue by CodeContent** [tpwd/ke_search#14]
Hi,

in one project we need the $this->conf array in the hook "modifyFilters":

        // hook to modify filters
        if (is_array($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['ke_search']['modifyFilters'])) {
            foreach ($GLOBALS['TYPO3_CONF_VARS']['EXTCONF']['ke_search']['modifyFilters'] as $_classRef) {
                $_procObj = GeneralUtility::makeInstance($_classRef);
                $_procObj->modifyFilters($this->filters, $this, $this->conf);
            }
        }

Without these change:
We add some information to hidden filters, but actually we cannot differentiate normal filters from hidden filters, because only $this->filters is given to the hook. The conf-Array is protected, so there is always an error:

Cannot access protected property TeaminmediasPluswerk\KeSearch\Lib\Filters::$conf

Thanks a lot!
Martin

**Comment by christianbltr** [comment]
You should be able to access the "conf" array by ` $this->pObj->conf;`

In opposite to `$this->conf`, ` $this->pObj->conf` is not protected but public.
