### ISSUE TITLE
Pages related to system categories contain 3 symbols will not displayed on filtered results after click by the category link. Why?

### ISSUE THREAD

**Issue by AALukashev** [tpwd/ke_search#141]
I have some categories like iOS, web. They are visible on filters (iOS (3), Web (1)), but entries will not displayed on filtered results after click by the category link. Why?

TYPO3 9.5.31
ke_search version 4.0.2 / stable

Settings:
ft_min_word_len = 3
searchWordLengh = 3

Also I changes 4 to 3 inside .php and .ts files

Could you please clarify how to display entries related to short system categories on filtered results?

**Comment by AALukashev** [comment]
Solved. It works from the box. Just need use "syscat1" on tag instead of human readable tag. Sorry for disturbing. Good luck!

**Comment by christianbltr** [comment]
Thanks for clarifying.

Just for the records: Here are some notes about naming of the tags (step 3): https://docs.typo3.org/p/tpwd/ke_search/main/en-us/Filters/Setup.html
