### ISSUE TITLE
Using EXT:news tags (table tx_news_domain_model_tag) for filtering

### ISSUE THREAD

**Issue by format-gmbh** [tpwd/ke_search#143]
I would like to use the tags of the news extension for filtering, analogous to the possibility of using system categories as filters. Is there already a solution for this?

**Comment by christianbltr** [comment]
Yes, that is already possible. If a tag is assigned to a news record, a ke_search tag will be created automatically.

> Example: If you want to filter for seasons, you can use the news categories "summer" and "winter". In ke_search you will then have to add the filter options eg. "All about the summer" and "Winter stuff" with the tags corresponding to the categories names: "summer" and "winter". Make sure the categories and the ke_search tags are spelled the same. For tags and keywords it's the same principle.
> 
> Tags will be generated by applying the rules for tags (no spaces and special characters). For example, if you have category "Blue cars!", a tag named "Bluecars" will be created.

from https://docs.typo3.org/p/tpwd/ke_search/main/en-us/Indexing/IndexerTypes/News.html

You will then need to create a filter and filter options yourself and use the tag which has been created automatically (in this example "Bluecars").

**Comment by format-gmbh** [comment]
The documentation is probably not up to date on this topic: 
You can assign a filter to a category in the "Search" tab (field "tx_kesearch_filter"). When you save the category afterwards, a new filter option is automatically added to the filter. 
And in the same way I expected this for news tags, but didn't find it, so I assumed that using news tags as filters is not possible at all.
