### ISSUE TITLE
Link to PDF files are wrong

### ISSUE THREAD

**Issue by MalikZohaib** [tpwd/ke_search#146]
Hi,
Links to all indexed pdfs files in search results are leading to 404 even though pdf files exists. I tried to debug it and found that here https://github.com/tpwd/ke_search/blob/master/Classes/Lib/SearchHelper.php#L251 file path is passed through rawurlencode which encodes the whole url of pdf while it should have to encode only title of the pdf. 

Here is an example of path before and after passing through L251.
<img width="327" alt="image" src="https://user-images.githubusercontent.com/12460091/219605054-a1a1c42b-d2d5-4656-9af6-0c908cd64632.png">

**Comment by christianbltr** [comment]
Thanks, the patch is merged and the fix will be in the next version.
