### ISSUE TITLE
Services.php may leads to Errors after Cache Clearing

### ISSUE THREAD

**Issue by Schweriner** [tpwd/ke_search#15]
TYPO3: 11.5.2
ke_search: 4.1.0

The /Configuration/Services.php is using ExtensionManagementUtility::isLoaded('dashboard') which may leads to errors when the System Cache is cleared in the Installtool or by installing extensions.
`static::$packageManager->isPackageActive() on null"`
This is because the ExtensionManagementUtility is probably not already loaded when calling the Services.php so there is no PackageManager injected yet.

**Comment by SruthiKumar333** [comment]
Is there any update regarding this issue? Happened to reproduce the same issue on upgrading typo3 11.5.1 to 11.5.2.

**Comment by christianbltr** [comment]
I could not reproduce this issue. Could explain a bit deeper how to reproduce this?

This is what I did:
1. Opened two tabs with the TYPO3 backend, one with the `Maintanance` module, one with the `Dashboard` module.
2. Cleared the system cache in the `Maintanance` module in one tab.
3. Reloaded the dashboard in the other tab. No error is shown.

I tried this with TYPO3 11.5.2 and 11.5.3

**Comment by TaiPan37** [comment]
Hi!
I can reproduce the error in the following configuration:
- ddev and docker with php 7.4
- TYPO3 11.5.3
- ke_search-master 4.1.0
After installing ke_search, the error message appears immediately in frontend and backend. If I undo the installation, TYPO3 works again as usual.

**Comment by TaiPan37** [comment]
Addition: As long as the extension folder is stored in the extension directory, the error remains. Only if the folder was deleted, the error disappears.

**Comment by christianbltr** [comment]
Are you using the "classic" installation method or via composer?

**Comment by SruthiKumar333** [comment]
I am using non-composer mode installation.

**Comment by TaiPan37** [comment]
I am using composer
