### ISSUE TITLE
Is it possible to sort search results by a custom mask field, like a custom date?

### ISSUE THREAD

**Issue by MCodes96** [tpwd/ke_search#153]
Unfortunately I wasn't able to find anything clear on the topic online.

**Comment by christianbltr** [comment]
This is not possible by configuration only, but I would see two possible solutions for this requirement:

* Use a hook in the page indexer to set the `sortdate` in the index table to the desired value or fill that value in your custom indexer.
* Add a column in the index (like `my_custom_date`), set that date in the page indexer hook or in your custom indexer and add that column as custom sort field as described in https://docs.typo3.org/p/tpwd/ke_search/main/en-us/Configuration/Sorting.html#sorting-own-options
