### ISSUE TITLE
In fluid request missing from rendering context results in localization not working TYPO3 12.4 / PHP 8.1

### ISSUE THREAD

**Issue by stigfaerch** [tpwd/ke_search#159]
Since request is missing from the renderingContext in Fluid, language cannot be found from site attribute of the request, and therefore localization does not work.

**Comment by stigfaerch** [comment]
On a side note. Even though if this is fixed, fetching translation for ke_search results in a file with no labels, even though the labels are translated in crowdin.
My current solution is to download the translation files from crowdin and then override with for example:
$GLOBALS['TYPO3_CONF_VARS']['SYS']['locallangXMLOverride']['da']['EXT:ke_search/Resources/Private/Language/locallang.xlf'][] = // path to danish translation file //

**Comment by christianbltr** [comment]
The crowdin issue should be fixed now.
