### ISSUE TITLE
[FEATURE] Hook bevor 'additionalResultMarker'

### ISSUE THREAD

**Issue by ste101** [tpwd/ke_search#16]
Hook `additionalResultMarker` is called for every search element (resultrow) e.g. 10 times.
What about a hook that is called only one time bevor the search and could be used in every resultrow or in `additionalResultMarker`?
This could save database calls.

**Comment by brotkrueml** [comment]
Can you describe the scenario?

I use the `additionalResultMarker` hook mostly for copying the value from additional fields to the result markers (which does not involve database calls). Hence the question. Maybe I miss something.

**Comment by christianbltr** [comment]
Yes of course, it would be possible to add such a hook. 

Could you give an example where you would see the use case for such a hook?

**Comment by brotkrueml** [comment]
Just my 2 cents: Shouldn't we go for PSR-14 events now? This is a much cleaner approach. And transitioning the existing hooks over time to events?

**Comment by christianbltr** [comment]
Yes, I also thought about that. But for backwards compatibility I would propose to leave the existing hooks untouched (besides marking them as deprecated) for quite some time and add PSR-14 events additionally.

**Comment by christianbltr** [comment]
I'm closing this for now as there is now use case given for the original request. Please feel free to comment if you think this is not right and give a use case for the original request.
