### ISSUE TITLE
Custom title and meta data for pages created automatically based on tags

### ISSUE THREAD

**Issue by AALukashev** [tpwd/ke_search#163]
Hello!

Is it possible to set custom title and meta data for pages like this: https://somedomain.com/page_with_filter/tag which contains all entries related to filtered data by a tag?

Regards,
Alexander.

**Comment by christianbltr** [comment]
I'm not sure what you want to achieve. Do you want to know how to create a "speaking URL" which shows all search results for a given tag? In this case, does this help?
https://docs.typo3.org/p/tpwd/ke_search/main/en-us/Configuration/RoutingSpeakingUrls.html#simple-example

**Comment by AALukashev** [comment]
Thank you for the reply. 

We have pages contain cases related to some technologies implemented as filters. Something like this.

https://somedomain.com/page_with_filter/dotnet
https://somedomain.com/page_with_filter/angularjs
https://somedomain.com/page_with_filter/autotests

Each page like https://somedomain.com/page_with_filter/dotnet collect pages related to case1, case2, case3, etc.

Cases exist inside CMS.

Pages like https://somedomain.com/page_with_filter/dotnet does not exist on CMS as pages, because this is a filter page based on categories like dotnet, angularjs, autotests, etc.

And pages like https://somedomain.com/page_with_filter/dotnet has no interface on CMS for managing of SEO things.

I modified init() in Pluginbase.php.  A tag is a filter.

```
		    /** @var \TYPO3\CMS\Core\Page\PageRenderer $pageRenderer */
            	    $pageRenderer = GeneralUtility::makeInstance(\TYPO3\CMS\Core\Page\PageRenderer::class);
		    $pageRenderer->setMetaTag('property', 'description', $GLOBALS['TSFE']->tmpl->setup_constants[$tag]['description']);
            	    $pageRenderer->setMetaTag('property', 'keywords', $GLOBALS['TSFE']->tmpl->setup_constants[$tag]['keywords']);
            	    $pageRenderer->setTitle($GLOBALS['TSFE']->tmpl->setup_constants[$tag]['title']);
		}
```

And add some string into TS placed to parent page collected pages with cases with  assigned filters.

```
dotnet.title = .net
dotnet.description = .net
dotnet.keywords = .net
angularjs.title = angularjs
angularjs.description = angularjs
angularjs.keywords = angularjs
autotests.title = autotests
autotests.description = autotests
autotests.keywords = autotests
```

These changes allow to add meta data and custom title for dynamically generated pages. For similar pages like this.

https://somedomain.com/page_with_filter/dotnet
https://somedomain.com/page_with_filter/angularjs
https://somedomain.com/page_with_filter/autotests

So we can close the task as I think.
