### ISSUE TITLE
Undefined array key "catdoc" in Doc.php line 93

### ISSUE THREAD

**Issue by format-gmbh** [tpwd/ke_search#171]
The error occurs when manually starting the indexer in the backend:
`PHP Warning: Undefined array key "catdoc" in vendor/tpwd/ke_search/Classes/Indexer/Filetypes/Doc.php line 93`

TYPO3 12.4.2
PHP 8.2.1
ke_search: 5.0.2

**Comment by rsiefert** [comment]
Just for your information, I have the same error in a live website. ke_search installed by extention manager in backend.
Core: Error handler (BE): PHP Warning: Undefined array key "catdoc" in ... [TYPO3 folder] ... /typo3conf/ext/ke_search/Classes/Indexer/Filetypes/Doc.php line 93

TYPO3 12.4.4
PHP 8.2.8
ke_search 5.0.2

Error is issued when calling the indexer, whether manually or by the sheduler. The line 93 belongs to the call of the pdftotext commandline tool.

**Comment by moritz-ngo** [comment]
This issue affects both `v5.0.2` and `v4.6.6` with TYPO3 CMS 11.5.30 and PHP 8.1

**Comment by moritz-ngo** [comment]
After some debugging, I realized, that this is not necessarily a bug in EXT:ke_search, but rather a configuration issue. Please make sure, that `catdoc` is installed and the path to the executable is properly configured.  
If you're using ddev, you may have to update your `ddev/config.yaml`
```
# ...
webimage_extra_packages: 
    - catdoc
# ...
```

**Comment by ecosmox36** [comment]
@moritz-ngo thanks for your analyzing but i guess the cause is a different one.

Missing applications are dropping a different error message.
This Warning here is more a syntaxproblem under php >= 8.0, i guess the required "Null Coalesce Operator" is missing here:

https://github.com/tpwd/ke_search/blob/14fa0703c2469e04eb398be4ae6268ec6ad6e720/Classes/Indexer/Filetypes/Doc.php#L93

And should be more like this 
```php

$catdocCommand = $this->app['catdoc'] ?? [];

if(!empty($catdocCommand))
   $cmd = "{$catdocCommand} -s8859-1 -dutf-8 $fileEscaped > $tempFileName";
```

**Comment by christianbltr** [comment]
This has now been fixed.

A check if `catdoc` is available is already implemented. If it is not available an error is written to the log and a message "Warning: There have been errors. Please refer to the error log (typically in var/log/)" is printed.
