### ISSUE TITLE
Exclude filters from cHash validation

### ISSUE THREAD

**Issue by christianbltr** [tpwd/ke_search#187]
When filters are used and cHash validation is enable, a 404 error will be thrown.

It is possible to exclude filter parameter from cHash validation manually to avoid that error, but that is inconvenient, see

[404 when searching (caused by cHash error due to enforceValidation)](https://github.com/tpwd/ke_search/blob/master/Documentation/Configuration/Avoid404Error.rst#example)

It would be good to have a solution where the filter parameters are excluded from the cHash validation automatically.

see also #149

**Comment by Hawkeye1909** [comment]
Hi @christianbltr!

As I wrote in #149 you can exclude all filter parameters by adding this:
`
$GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'] = array_merge($GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'], ['^tx_kesearch_pi1[filter_']);
`
This would be in addition to your exclusion in ext_localconf.php.

To exclude all parameters associated with ke_search, you could also simply add:
`
$GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'] = array_merge($GLOBALS['TYPO3_CONF_VARS']['FE']['cacheHash']['excludedParameters'], ['^tx_kesearch_pi1']);
`
This would replace your solution all together...

**Comment by christianbltr** [comment]
@Hawkeye1909 thanks! I simply overlooked the caret in your example. I think that's a very nice way to exclude all the ke_search parameters from cHash validation without the need to configure that manually for the filters. That configuration is now included in ke_search and will be in the next version after 5.0.4
