### ISSUE TITLE
TYPO3 List view in backend is becoming slow

### ISSUE THREAD

**Issue by DanielSiepmann** [tpwd/ke_search#190]
This is when table tx_kesearch_stat_word is filled. The table has no index on pid.
That results in slow sql queries whenever a page is opened in list view.

One can say this is an issue of TYPO3, not adding the index for all tables. But right now it is easier to fix that within EXT:ke_search.

I'll provide a PR soon.

**Comment by DanielSiepmann** [comment]
I've opened an issue on TYPO3: https://forge.typo3.org/issues/102179

**Comment by christianbltr** [comment]
Thanks. In https://forge.typo3.org/issues/102179 it is proposed to let TYPO3 auto-generate the indexes, but the table `tx_kesearch_stat_word` does not have a TCA definition so that would not work here. So the index for `pid` for needs to be added in the `ext_tables.sql` file.

**Comment by DanielSiepmann** [comment]
You're right. The project we have inherited has TCA for that table. So the extension itself should not be slow, it is an issue with the instance.
