### ISSUE TITLE
Adding filter options is not possible if "backend enforce content security" policy is enabled

### ISSUE THREAD

**Issue by christianbltr** [tpwd/ke_search#194]
In TYPO3 12 if the feature toggle "Security: backend enforce content security policy" is enabled it is not possible to add filter options to filters.

![Auswahl_044](https://github.com/tpwd/ke_search/assets/11410553/79e83dc5-f768-4481-92fe-feff93839cbe)
![Auswahl_043](https://github.com/tpwd/ke_search/assets/11410553/bb3a2140-9ed8-4932-b2f9-e7a8fb7e2d64)

**Comment by christianbltr** [comment]
As of today I'm not able to reprouce this (Tested with TYPO3 12.4.0 and ke_search 5.1.0 and with TYPO3 12.4.1 and ke_search 5.4.1) in a ddev environment. So I'm closing this.

**Comment by Inovanet** [comment]
By adding $GLOBALS['TYPO3_CONF_VARS']['SYS']['features']['security.backend.enforceContentSecurityPolicy'] = false; in for example a plugin in ext_localconf adding filters is working.

It's also possible to add $GLOBALS['TYPO3_CONF_VARS']['BE']['contentSecurityPolicyReportingUrl'] = 'http://example.com/'; to further restrict / allow CSP.
