### ISSUE TITLE
No results found(TYPO3 11.5)

### ISSUE THREAD

**Issue by Pravin0711** [tpwd/ke_search#196]
i have just upgrade my typo3 version 10.4 to 11.5. In typo3 10.4 ke_search extension working properly. But after upgrade 11.5 it's not working correctly. when i enter any word everytime i get `No results found.` see attached screenshot.

![Screenshot (30)](https://github.com/tpwd/ke_search/assets/137781747/fb6b8804-2e7c-4fa1-b69f-b9c393c402f8)

![Screenshot (31)](https://github.com/tpwd/ke_search/assets/137781747/dcee1ab6-6374-4ded-b015-fdc0d8ae0f44)

Please help me
How can i fix this issue.

**Comment by christianbltr** [comment]
Could you try deleting the table `tx_kesearch_index` and run the database compare tool again?

**Comment by Pravin0711** [comment]
> Could you try deleting the table `tx_kesearch_index` and run the database compare tool again?

still get `No results found`
