### ISSUE TITLE
Searching for a word with an @ in the sword returns an error

### ISSUE THREAD

**Issue by robsonrobi** [tpwd/ke_search#201]
It is not possible to search for example an email adress.

It results in Could not fetch search results. Error #1605867846

**Comment by christianbltr** [comment]
I could not reproduce this in a standard installation but when using InnoDB as storage engine for the table `tx_kesearch_index`. 

Are you using InnoDB?

See also https://github.com/teaminmedias-pluswerk/ke_search/issues/226

In this case I would propose to use the new "Additional word character" feature and add the @ as an additional word character as described in https://docs.typo3.org/p/tpwd/ke_search/main/en-us/Configuration/AdditionalWordCharacters.html

**Comment by christianbltr** [comment]
See also https://docs.typo3.org/p/tpwd/ke_search/main/en-us/Configuration/StorageEngine.html
