### ISSUE TITLE
 Issue with Disabled Files Appearing in Search result

### ISSUE THREAD

**Issue by kbenyedder** [tpwd/ke_search#206]
Dear Team,

I hope this message finds you well.

I am experiencing an issue with the TYPO3 version 11 CMS, running on PHP 8.0.
Despite deactivating certain files in the uploads content element, they continue to appear in the search results.

This is a critical concern for us, and we require your assistance to resolve it as soon as possible.

Thank you very much for your attention to this matter.

Best regards,
Beny

![image](https://github.com/tpwd/ke_search/assets/66422450/69398353-5e23-4d9a-a84f-5d428d308ce1)

**Comment by kbenyedder** [comment]
@christianbltr  can you please take care of it

**Comment by christianbltr** [comment]
Thanks for reporting. This has been fixed and will be in version 5.2.1 which will be released today.
