### ISSUE TITLE
executeQuery()

### ISSUE THREAD

**Issue by bm1-phillip** [tpwd/ke_search#208]
There is an error when I try to open the page settings.

- TYPO3 11.5.33
- ke_search: 5.2.1

`Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to undefined method TYPO3\CMS\Core\Database\Query\QueryBuilder::executeQuery() \| Error thrown in file /var/www/html/public/typo3conf/ext/ke_search/Classes/Backend/Filterlist.php in line 105.`

The change of 
[->executeQuery();](https://github.com/tpwd/ke_search/blob/d7e9f56d519ef03ddb4e2321f63e761f6d3f1aca/Classes/Backend/Filterlist.php#L105)
in
`->execute();`
fixes the error.

**Comment by christianbltr** [comment]
When you opened this issue you wrote "TYPO3 11.5.0" which is where the bug appears.

Are you sure it does not work with TYPO3 11.5.33?

I could reproduce the issue in TYPO3 11.5.0 but not in 11.5.33.

executeQuery() has been introduce in doctrine/dbal a while ago (see also https://www.doctrine-project.org/2021/03/29/dbal-2.13.html) and works at least with TYPO3 11.5.11. 

This version requirement was set in ext_emconf.php but was missing in composer.json, this has now been added.

**Comment by bm1-phillip** [comment]
Hi, you can close the ticket. The error occurred due to two previously unnoticed mistakes.

In the composer, a ^ was missing before a ^11. That's why the version. And the SCSS files were moved to Public, and a path was not corrected properly.

Unfortunately, I only figured this out just now.
