### ISSUE TITLE
Make dashboard optional

### ISSUE THREAD

**Issue by mikestreety** [tpwd/ke_search#21]
Love the dashboard widgets, however, there are a couple of clients of mine that don't use the dashboard and the latest update is installing it regardless.

is there a way of including the widgets if the dashboard is installed, but not having it as a "requirement"? Maybe move it to the "suggests" sections of composer & ext_emconf and having a conditional to check if it is installed?

IMO the dashboard is something that should be chosen to be installed or not and is not a _requirement_ for KE Search to work.

Thanks again and keep up the amazing work 👍

**Comment by christianbltr** [comment]
Thanks a lot.

Unfortunately in latest versions of TYPO3 it seems not to be possible to reliably check if the dashboard extension is installed before registering the widgets (registering the widgets without dashboard installed throws an error). The only solution I currently see is to require the dashboard to be installed, see also https://github.com/tpwd/ke_search/issues/15#issuecomment-985470346

**Comment by devtroll** [comment]
Wouldn't it be better to remove the dashboard completely from composer.json? This way I get the dashboard in my development environment even though I don't want it.

**Comment by christianbltr** [comment]
The patch removes `dashboard` from the `require` section and moves it to the `suggest` section. So it should be installed automatically anymore. 

https://github.com/tpwd/ke_search/pull/30/files#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34R24

Suggesting dashboard seems reasonable because ke_search provides dashboard widgets.

**Comment by mikestreety** [comment]
Thanks for this. 'suggests' is a perfect place for it
