### ISSUE TITLE
error on result page with Typo3 12 Could not fetch search results. Error #1605867846

### ISSUE THREAD

**Issue by asche76** [tpwd/ke_search#210]
got this error with Typo3 12, ke_search 5.1.3 / 5.2.1 php 8.2
Could not fetch search results. Error #1605867846
the auto results without search are displayed normal.
has anyone an idea?
regards

**Comment by christianbltr** [comment]
This error message is generated in https://github.com/tpwd/ke_search/blob/840f910be3664db07312a325571cf5ebb98193cd/Classes/Lib/Db.php#L140

Could you set the debug level for ke_search to "ERROR" (in the extension settings) and see what's in the log file (in var/log/ in your installation)?

**Comment by asche76** [comment]
in var/customer/logs/...error.log  is nothing with ke_search only some domain stuff -
but in typo3temp/var/log typo3_kesearch_43801b2f50.log is following:
Fri, 26 Jan 2024 09:27:50 +0000 [ERROR] request="1d44007875057" component="Tpwd.KeSearch.Lib.Db": An exception occurred while executing a query: Can't find FULLTEXT index matching the column list #0 /var/customers/webs/xyz/vendor/doctrin

**Comment by christianbltr** [comment]
Are you using some kind of custom code which maybe changes the columns which are fetched from the database? 
If not, could you try to delete the index table and recreate it using the TYPO3 database compare tool?

**Comment by asche76** [comment]
sorry for the late reply - fantastic it works - many thanks
best regards
