### ISSUE TITLE
Make pagination configurable

### ISSUE THREAD

**Issue by criwe** [tpwd/ke_search#213]
Hi!

It would be a cool thing to have options to configure the pagination, i. e. "maximumNumberOfLinks" (to set the amount of numbers shown) like news does (see https://docs.typo3.org/p/georgringer/news/main/en-us/Reference/TypoScript/GeneralSettings.html#list-paginate). 

Many greetings
Christoph

**Comment by christianbltr** [comment]
That is already possible in the plugin configuration.

![Auswahl_065](https://github.com/tpwd/ke_search/assets/11410553/f2bb343b-48c9-463a-b3d7-bee6de0c7b27)
