### ISSUE TITLE
Exception after update to version 5.2.1

### ISSUE THREAD

**Issue by fischhase** [tpwd/ke_search#214]
Dear ke_search team,

thanks for your great extension. Unfortunately I get an error after updateing to version 5.2.1 on TYPO3 12.4.10. When I try to edit existing  plugins or placing a new one, typo3 throws an exception:
"PHP Warning: Array to string conversion in /usr/www/users/wieses/typo3/typo3_src-12.4.10/typo3/sysext/core/Classes/Localization/LanguageService.php line 178"

It does'nt matter, wich plugin I choose. The site has 4 languages in site config. I tested PHP Version 8.1 - 8.3.
The function of the plugins are ok. I can search and get a resultlist. But editing isn't possible, anymore.

If you need mor information, please let me know.

Martin

**Comment by christianbltr** [comment]
I could not reproduce this issue in my testing environment. Could you post the full error stack trace?
