### ISSUE TITLE
Pagination: Avoid duplicate url to page-1

### ISSUE THREAD

**Issue by ste101** [tpwd/ke_search#22]
Current Behavior
Currently the first page of pagination is available via two urls - "/seach/" and "/search/page-1/".

Expected behavior/output
The link to the first page of pagination should not contain the segment "/search/page-1/".

Is there a way?

**Comment by ste101** [comment]
This patch did it for my:
```
diff -ru ke_search_4.2.0/Classes/ViewHelpers/LinkViewHelper.php ke_search/Classes/ViewHelpers/LinkViewHelper.php
--- ke_search_4.2.0/Classes/ViewHelpers/LinkViewHelper.php	2021-12-10 14:34:08.000000000 +0100
+++ ke_search/Classes/ViewHelpers/LinkViewHelper.php	2021-12-15 23:38:24.000000000 +0100
@@ -53,11 +53,14 @@
             );
         }
 
+        if ($piVars['page'] == 1) {
+            unset($piVars['page']);
+        }
+
         $linkedContent = $this->renderChildren();
         if (empty($content)) {
             $content = $linkedContent;
```
Is this a reasonable solution?

**Comment by brotkrueml** [comment]
Can you describe the scenario where you have those two URLs (with and without page if page=1)? When searching initially via the Searchbox plugin I get always the page=1 parameter in URL.

Personally I don't like personally unsetting the page, if the value is 1 - I feel it to be unclean, as the code relies on separate places of the page set and it is also set initially to 1 if not defined:
https://github.com/tpwd/ke_search/blob/master/Classes/Lib/Pluginbase.php#L323

Also the URL does not matter, as a search page should never be indexed by search engines by various reasons (if you fear duplicate content).

**Comment by ste101** [comment]
> Can you describe the scenario where you have those two URLs (with and without page if page=1)? When searching initially via the Searchbox plugin I get always the page=1 parameter in URL.

If 'showTextInsteadOfResults' is not set you will get a result without a search word.
Then this page could be called with the page parameter and witout.

> Personally I don't like unsetting the page at this place, if the value is 1 - I feel it to be unclean, as the code relies on separate places of the page set and it is also set initially to 1 if not defined: https://github.com/tpwd/ke_search/blob/master/Classes/Lib/Pluginbase.php#L323
> 
> Also the URL does not matter, as a search page should never be indexed by search engines by various reasons (if you fear duplicate content).

I set the search page to 'noindex'.

**Comment by brotkrueml** [comment]
I see. What would be the benefit of this change (as SEO is not relevant)?

I also have `sword=` (empty) and `resetFilters=0` as parameters, so that should also be removed to be clean (when clicking on `Find` without search word and filters.

**Comment by ste101** [comment]
I think it is stringent then.
Removing emtpy parameter in general would be nice I think.

**Comment by christianbltr** [comment]
I think it should be save to remove the page paramater in the link viewhelper if it links to the first page because it will be initialized to page 1 in Pluginbase --> init() if it is empty.
This has been merged into current master and will be in the next version.
