### ISSUE TITLE
Wrongly configured file indexer directory paths throws error

### ISSUE THREAD

**Issue by philip-hartmann** [tpwd/ke_search#225]
Version: tpwd/ke_search@v4.6.6

Description:

A wrongly configured file indexer directory throws an error on execution and stopps the indexing task.

````
In LocalDriver.php line 294:

Folder "NON_EXISTENT_FOLDER_PATH" does not exist.
```

**Comment by christianbltr** [comment]
Fixed in current master, will be in next version after 5.4.1
