### ISSUE TITLE
Filter options not selectable in CE of ke_search

### ISSUE THREAD

**Issue by Inovanet** [tpwd/ke_search#236]
Created filter options are not selectable in the content element for ke_search. There are 3 filter options present but in the configuration for the content element none of them is visible.

![filteroptions](https://github.com/tpwd/ke_search/assets/25638983/fba16166-dc9a-4149-966a-1976531d3d07)
![filter](https://github.com/tpwd/ke_search/assets/25638983/10dc324f-3643-4039-9a99-3cba84de018a)

System used:
TYPO3 12.4.13
ke_search 5.5.0
PHP 8.1.29

**Comment by christianbltr** [comment]
Did you check if the record storage page is set to the right system folder?

![Auswahl_091](https://github.com/user-attachments/assets/fc4ae49f-f09f-44fe-9705-aab02c40c1c2)

**Comment by Inovanet** [comment]
The storage folder has already been set.

![filterbottom](https://github.com/user-attachments/assets/8b05453f-dc86-46c0-b274-866a3659f3c2)

**Comment by christianbltr** [comment]
Did you also create filters or only filter options? You need to create filter records first, then add filter options to the filters. Filter options are meant to be created inside a filter, not stand-alone.

![Auswahl_092](https://github.com/user-attachments/assets/8514e41a-2535-45a5-814c-b4fe52d855c9)

![Auswahl_093](https://github.com/user-attachments/assets/2a511482-fb76-4f80-9019-c68c80fc374a)

Also: Having "Startseite" configured as record storage additionally to the "Search data" folder for the plugin seems strange. Are you sure that's where your search configuration is? If you don't have any indexer records or filter records stored on "Startseite" you can safely remove it here.

**Comment by christianbltr** [comment]
This may be related to #231.
Does it work if you disable the feature toggle "Security: backend enforce content security policy" as described in #194?

**Comment by Inovanet** [comment]
Added a comment in #194
