### ISSUE TITLE
[BUG] Unnecessary link parameter 'tx_kesearch_pi1[page]' in filter rendertype 'list'

### ISSUE THREAD

**Issue by ste101** [tpwd/ke_search#24]
I can see the parameter tx_kesearch_pi1[page] in the links of a filter of rendertype 'list'.
I think this parameter is unnecessary.

I could get rid of this parameter after commenting out the line 539
```
$localPiVars = $this->piVars;
```
in /Classes/Lib/Pluginbase.php

I don't know if there are side effects but till now I can't see one.

**Comment by christianbltr** [comment]
Could you explain what would be the benefit of this? 

I think this is similar to https://github.com/tpwd/ke_search/issues/22#issuecomment-1017391657

Why does the generated URL matter in this case?

**Comment by ste101** [comment]
E.g. you make a search, then use the pagination to click through till page 5.
If you click now on a link of a list filter then you will see the filtered result at pagination page 5.
If the filtered result is less than 5 pages the result shows an empty result. 
I think it is much better to start with pagination page 1.

**Comment by christianbltr** [comment]
Thanks for explaining, l could reproduce this issue.
This has been fixed in current master.
