### ISSUE TITLE
Undefined array key: Argument #2 ($context) must be of type array, null given

### ISSUE THREAD

**Issue by JensVollmer** [tpwd/ke_search#243]
ke_search 5.1.1
TYPO3 11.5.39

After updating to 5.1.1 the scheduler/indexer task fails if `$this->cachedPageRecords[$language_uid][$uid]` is not set.

TypeError
Psr\Log\AbstractLogger::debug(): Argument #2 ($context) must be of type array, null given, called in ke_search/Classes/Indexer/Types/Page.php on line 804

[Classes/Indexer/Types/Page.php]
```php
@@ -803,23 +795,11 @@ public function getPageContent($uid)
                    $this->counter++;
                } else {
                    $this->pObj->logger->debug(
                        'Skipping page "' . $pageTitle . '" (UID ' . $uid . ', L ' . $language_uid . ')'
                        'Skipping page "' . $pageTitle . '"',
                        $this->cachedPageRecords[$language_uid][$uid]
```

**Comment by tgaertner** [comment]
correct version is 5.5.1
Same on TYPO3 12.4.19
