### ISSUE TITLE
Compatible in Typo3 13?

### ISSUE THREAD

**Issue by MRothenburger** [tpwd/ke_search#245]
Hi,
does anyone know if I can use this plugin in Typo3 v.13? Or is there already a plan for a new version?

Thanks in advanced!
Kind regards,
Martina

**Comment by christianbltr** [comment]
Yes, there will be a version for TYPO3 13. Development branch is https://github.com/tpwd/ke_search/tree/typo3-13. There's no fix schedule for the release date, but the plan is to release it together with or shortly after TYPO3 13 LTS.
