### ISSUE TITLE
Startingpoint field not visible in v13

### ISSUE THREAD

**Issue by s2b** [tpwd/ke_search#251]
In my v13 installation, the Startingpoint (`pages`) tt_content field is not visible anymore for search plugins. My guess would be that this is related to the switch from `list_type` to `CType`. As this is necessary to configure the plugins properly, it should be added again.

In my project I use the following TCA workaround for now:

```php
ExtensionManagementUtility::addToAllTCAtypes(
    'tt_content',
    'pages',
    'ke_search_pi1,ke_search_pi2,ke_search_pi3',
    'after:pi_flexform',
);
```

**Comment by bh-teufels** [comment]
Same here on TYPO3 12.4.22 
ke_Search 6.0.0

after documentary should:
Fill in the field Record Storage Page in the Tab Plugin > General with the folder that you created in step 2 (our example: Search data).

but Record Storage Page missing in "Searchbox" Plugin
