### ISSUE TITLE
Indexer not working

### ISSUE THREAD

**Issue by wini2** [tpwd/ke_search#256]
After I cleared the search index and started to rebuild the index, I get

The MySQL indexes in the table 'tx_kesearch_index' are disabled. Searching in the frontend will not work. 

In FE I get "Could not fetch search results. Error #1605867846"

After pressing button Start full indexing in th BE I get 

TYPO3\CMS\Core\Utility\GeneralUtility::trimExplode(): Argument #2 ($string) must be of type string, null given, called in /home/www/mywebsite/vendor/tpwd/ke_search/Classes/Indexer/Types/File.php on line 97

Indexer configuration and Scheduler task are created.

Is it a bug or did I miss something

TYPO3 13.3/ke_search 6.0.1

**Comment by christianbltr** [comment]
I assume that in your "Files" indexer configuration there no directories given which should be indexed. Please try to deactivate hat indexer configuration and run the indexer again. That should re-create the MySQL indexes.

**Comment by wini2** [comment]
Thanks for your help. It was my fault. It seems that my classes need more diopter ;-)
