### ISSUE TITLE
Crowdin integration fails

### ISSUE THREAD

**Issue by prathers** [tpwd/ke_search#261]
The project at Crowdin has issues: https://crowdin.com/project/typo3-extension-kesearch/integrations/system/github

There is an unconfigured branch. In order to enable sync, please double-click on the necessary branch to create a configuration.

For help: https://support.crowdin.com/github-integration/

**Comment by christianbltr** [comment]
@prathers 

The configuration file `.crowdin.yml` was already there but somehow was not recognized anymore. After saving the configuration again in https://crowdin.com/project/typo3-extension-kesearch/integrations/system/github and synchronizing now the language files are show twice. Do you know if this is a known issue?

![Auswahl_021](https://github.com/user-attachments/assets/402e3af0-68a6-4c85-9e1d-ec9e0bfe0a91)

**Comment by christianbltr** [comment]
Thank you!

**Comment by christianbltr** [comment]
Looks good to me too, thank you!
