### ISSUE TITLE
ResourceDoesNotExistException on deleted files - join tables to check deleted status?

### ISSUE THREAD

**Issue by mikestreety** [tpwd/ke_search#42]
If I have the file indexer enabled and search for a file which has been deleted before reindexing, a `ResourceDoesNotExistException` is thrown when trying to render the thumbnail (sorry, was trying to get it into a succinct sentence!).

We have a file indexer watching a folder with PDFs. When one of these files was deleted, searching for a word contained in the document creates a TYPO3 exception.

![image](https://user-images.githubusercontent.com/354085/150555497-0ad20443-d4d7-4350-8b6d-49a28c27030b.png)

I narrowed this down to the image preview (but also, clicking the link takes you to a 404).

**The Question**

When retrieving the results from the database, is it possible to join the `deleted` and `hidden` fields from the original table to check, in real-time, if the record is hidden or deleted? This would prevent 404s being rendered in the list.

Alternatively, could a custom `<if>` be wrapped round the image to prevent it trying to render images that don't exist?

Sorry for the rambling, trying to offer constructive solutions!

**Comment by christianbltr** [comment]
Thanks for reporting. This has been fixed and will be in the next version.

File previews will not be rendered anymore if the image (or PDF) does not exist. Futhermore no link will be generated, but the result is still in the result list (not linked). That's the same behaviour as with pages or news when they get hidden or deleted between two indexing processes.
