### ISSUE TITLE
[FEATURE] Crowdin Translation Integration

### ISSUE THREAD

**Issue by sneopu** [tpwd/ke_search#47]
It would be nice to integrate the crowdin translation service. This would make it easy to contribute new languages.

See: https://docs.typo3.org/m/typo3/reference-coreapi/main/en-us/ApiOverview/Internationalization/TranslationServer/Crowdin.html

**Comment by christianbltr** [comment]
Translating via Crowdin is now possible:

https://crowdin.com/project/typo3-extension-kesearch
