### ISSUE TITLE
[ERROR] depends on "dashboard"

### ISSUE THREAD

**Issue by xerc** [tpwd/ke_search#53]
@ composer
> TYPO3 Exception #1519931815: The package "ke_search" depends on "dashboard" which is not present in the system.
> thrown in file `typo3/sysext/core/Classes/Package/PackageManager.php` [1110]

please make this dependency non breaking

**Comment by brotkrueml** [comment]
This was already fixed in master:
https://github.com/tpwd/ke_search/commit/fde43611006430c9e53b0adbc8d5f6fb4fe78ddd

See also changelog:
https://github.com/tpwd/ke_search/blob/master/ChangeLog#L23
