### ISSUE TITLE
Translation files missing

### ISSUE THREAD

**Issue by ste101** [tpwd/ke_search#67]
I made an update to 4.3.0 and now there are no translations in German of markers in SearchForm.html (searchwordDefault, reset_button, submit) and in ResultList.html.
Going back to 4.2.0 everything is fine. I updated the language files every time

**Comment by brotkrueml** [comment]
Okay, asked in the Slack channel: https://typo3.slack.com/archives/CMUG7C04F/p1644599117550009

**Comment by christianbltr** [comment]
Downloading the Crowdin translations from the translation server should work now (just tested it today). 

A directory had to be renamed in Crowdin which is fixed now: https://typo3.slack.com/archives/CMUG7C04F/p1645082726401329?thread_ts=1645079068.138579&cid=CMUG7C04F

**Comment by ste101** [comment]
Thank you
