### ISSUE TITLE
BUG: Upgrading to latest typo3 and ke_search makes faceted search unusable.

### ISSUE THREAD

**Issue by nikolas-schwarz** [tpwd/ke_search#74]
I have updated my TYPO3 to version 11.5.6 and ke_search 4.3.
If I try to use on of my filters the search results won't be limited by the used filter. I checked the documentation, I cleared the index and reindexed the content. 

An example:
If I search for a phrase the results I get back are 72 results. If I select on of the filters, the page reloads and the filter option is added to the url but the results are still 72. No filtering is happening.

Is there any other step, to update the filters and filter options?

**Comment by nikolas-schwarz** [comment]
Downgrading to Version 4.2.0 helped, filtering works

**Comment by christianbltr** [comment]
This has been fixed in 4.3.1 which has been released today.
