### ISSUE TITLE
All custom types indexed - one of them not found

### ISSUE THREAD

**Issue by dasoe** [tpwd/ke_search#79]
Hi all,
**thank you for this great extension!**

I have an issue I can not find out, I hope you can help: 
I have multiple custom indexers, all of which are indexed nicely. They also show up as filter options in Frontend. So actually I thought it should work. Still the custom indexer I added last (Courses) does not show results. All the others are fine.
I double-(actually quadruple) checked the installation and manual, re-set it on another server, compared DB entries, tried debug mode log (no entries)... Now I am out of ideas. Is there something I could have missed for that one indexer?

Any hint or idea would be greatly appreciated.
Have a good day!
oe

Screenshots:

![Screenshot from 2022-03-09 18-32-32](https://user-images.githubusercontent.com/11035176/157498074-2a0ecd61-55c3-4fc1-ab7a-b7512a96ac29.png)
---
![Screenshot from 2022-03-09 17-58-10](https://user-images.githubusercontent.com/11035176/157493251-d009dbf5-1ae0-481d-aa4b-067dae4acfed.png)
---
![Screenshot from 2022-03-09 18-21-29](https://user-images.githubusercontent.com/11035176/157496331-fc2a5c79-c8ef-4b73-9eac-9e83596be039.png)
---
![Screenshot from 2022-03-09 18-22-06](https://user-images.githubusercontent.com/11035176/157496330-55f17c55-1179-45a2-bd17-5cca257596b1.png)
---
![Screenshot from 2022-03-09 18-24-26](https://user-images.githubusercontent.com/11035176/157496629-a245f749-5f86-4a53-841b-c53c96cc9604.png)

**Comment by christianbltr** [comment]
From the screenshots one can see that you are filtering for the "Course" filter option. Did you check that the tags in the index records are set correctly and that the Filter option "Course" filters for the correct tag?

Do the "Course" results show up if you only use the full text search and not the filters?

**Comment by dasoe** [comment]
**Thanks for taking the time to help!**
As far as I understand the tags are set and indexed correctly (please see Screenshots including comparison to a working filter). But you are right: when I uncheck _markAllCheckboxes_ in Filters Object I do get results for Courses also!

To be sure to not have sth. like invisible characters or the like, I just re-typed the tag 'course' in Filter option, pasted it in custom indexer code, deleted search index an re-indexed. Same result, though. 

---
![Screenshot from 2022-03-11 09-56-24](https://user-images.githubusercontent.com/11035176/157835074-1ea1181b-51bd-4322-924e-f79c191662f9.png)
---
![Screenshot from 2022-03-11 09-55-49](https://user-images.githubusercontent.com/11035176/157835082-1a93b798-b70e-44fe-a959-8da88ad6c804.png)
---
![Screenshot from 2022-03-11 10-16-41](https://user-images.githubusercontent.com/11035176/157838131-d5bc5dd3-3c43-4f20-885a-e788a5b2e5d2.png)
---
![Screenshot from 2022-03-11 10-14-42](https://user-images.githubusercontent.com/11035176/157837867-e419f082-96ee-4814-a9a1-7318aa2f0ffb.png)

**Comment by christianbltr** [comment]
I saw that "course" is in the MySQL stop word list (https://dev.mysql.com/doc/refman/8.0/en/fulltext-stopwords.html).

Could you try to rename the tag to something different?

**Comment by dasoe** [comment]
You are my hero!
I did - and it works.

**Thank you so much, I would have never thought of that!**

**Comment by christianbltr** [comment]
Great. :+1: 
I think I will add a note about that in the documentation. Or maybe a check when a tag is created should be implemented. I will open a issue for that.
