### ISSUE TITLE
Indexing fails on unsupported files

### ISSUE THREAD

**Issue by AureliusHogan** [tpwd/ke_search#87]
```sh
 [ TYPO3\CMS\Core\Exception ]                                                    
  Unsupported file SPAR_Bester_Frische_Preis_KW52.pdf (application/octet-stream)  
```
When indexing reaches a file of this type, TYPO3 core imaging throws this error in typo3/sysext/core/Classes/Imaging/ImageMagickFile.php:189
and stops indexing.

**Comment by christianbltr** [comment]
Unfortunately I could not reproduce that issue. For my test I a renamed an ".exe" file to ".pdf". The indexing process does not stop. There is just no content indexed for that file.

Could you provide the test file which causes the error on your side?

Also, I'm not sure why the ImageMagickFile class is called here. In the class comment it says "Value object for file to be used for ImageMagick/GraphicsMagick invocation" and the indexer does not generate any images, it only uses "pdftotext" to fetch the content from PDF files.
