### ISSUE TITLE
Filters type - Checkboxes - Mark all checkboxes by default - dont work

### ISSUE THREAD

**Issue by agendartobias** [tpwd/ke_search#98]
I am using TYPO3 11.5.10 and ke_search 4.4.1 the option Mark all checkboxes by default wont preselect all filters in frontend.

I think this is a bug or am i doing something wrong?

**Comment by christianbltr** [comment]
Just tested this and it works in current master with TYPO3 11 in my test environment. But checkboxes will only be marked if there are results for the corresponding tag. Maybe there are no results for the tags of your filter options?

Example:

![Auswahl_045](https://user-images.githubusercontent.com/11410553/170654680-1d2b76a5-354b-4f87-b116-71af644c0b10.png)
